// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalf9MMkHej-SBMkXT3hOLH7DtrRgPRpE',
    appId: '1:943634336292:web:2bb8fc389ca9291b27a6b1',
    messagingSenderId: '943634336292',
    projectId: 'reciprocity-151c1',
    authDomain: 'reciprocity-151c1.firebaseapp.com',
    storageBucket: 'reciprocity-151c1.appspot.com',
    measurementId: 'G-7NJ9DN492X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnHd4prIlBdlCA1bGk2EUhgNPQojOaQ4I',
    appId: '1:943634336292:android:b993e4f42cea3d7027a6b1',
    messagingSenderId: '943634336292',
    projectId: 'reciprocity-151c1',
    storageBucket: 'reciprocity-151c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr3lNPU8Yq8j7UpNimuNPSo0nhboHdbLU',
    appId: '1:943634336292:ios:0a4e68413d6141b027a6b1',
    messagingSenderId: '943634336292',
    projectId: 'reciprocity-151c1',
    storageBucket: 'reciprocity-151c1.appspot.com',
    iosBundleId: 'com.example.reciprocity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr3lNPU8Yq8j7UpNimuNPSo0nhboHdbLU',
    appId: '1:943634336292:ios:0a4e68413d6141b027a6b1',
    messagingSenderId: '943634336292',
    projectId: 'reciprocity-151c1',
    storageBucket: 'reciprocity-151c1.appspot.com',
    iosBundleId: 'com.example.reciprocity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAalf9MMkHej-SBMkXT3hOLH7DtrRgPRpE',
    appId: '1:943634336292:web:7a35b420cbf1ec3a27a6b1',
    messagingSenderId: '943634336292',
    projectId: 'reciprocity-151c1',
    authDomain: 'reciprocity-151c1.firebaseapp.com',
    storageBucket: 'reciprocity-151c1.appspot.com',
    measurementId: 'G-CY45KV54DZ',
  );
}
